/*
 * GMO Aozora Net Bank Open API
 *
 * <p>Ph2.5向けに作成したもの</p> 
 *
 * API version: 1.1.10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// 振込入金口座入金明細情報 
type VaTransaction struct {
	// 振込入金口座ID 半角数字 振込入金口座を識別するID 
	VaId string `json:"vaId"`
	// 取引日 半角文字 YYYY-MM-DD形式 
	TransactionDate string `json:"transactionDate"`
	// 起算日 半角文字 YYYY-MM-DD形式 
	ValueDate string `json:"valueDate"`
	// 支店コード 半角数字 
	VaBranchCode string `json:"vaBranchCode"`
	// 支店名カナ 半角文字 
	VaBranchNameKana string `json:"vaBranchNameKana"`
	// 口座番号 半角数字 
	VaAccountNumber string `json:"vaAccountNumber"`
	// 口座名義カナ 半角文字 
	VaAccountNameKana string `json:"vaAccountNameKana"`
	// 入金金額 半角数字 
	DepositAmount string `json:"depositAmount"`
	// 振込依頼人名カナ 半角文字 
	RemitterNameKana string `json:"remitterNameKana"`
	// 仕向金融機関名カナ 半角文字 
	PaymentBankName string `json:"paymentBankName"`
	// 仕向支店名カナ 半角文字 
	PaymentBranchName string `json:"paymentBranchName"`
	// サービス企業名 全角文字 振込入金口座契約サービス企業名 
	PartnerName string `json:"partnerName"`
	// 摘要内容 全半角文字 該当データがない場合は項目自体を設定しません 
	Remarks string `json:"remarks,omitempty"`
	// 明細キー 半角数字 口座ID毎に設定される明細キー（明細データtimestamp（μs））
	ItemKey string `json:"itemKey"`
}
