/*
 * GMO Aozora Net Bank Open API
 *
 * <p>オープンAPI仕様書（PDF版）は下記リンクをご参照ください</p> <div>   <div style='display:inline-block;'><a style='text-decoration:none; font-weight:bold; color:#00b8d4;' href='https://gmo-aozora.com/business/service/api-specification.html' target='_blank'>オープンAPI仕様書</a></div><div style='display:inline-block; margin-left:2px; left:2px; width:10px; height:10px; border-top:2px solid #00b8d4; border-right:2px solid #00b8d4; transparent;-webkit-transform:rotate(45deg); transform: rotate(45deg);'></div> </div> <h4 style='margin-top:30px; border-left: solid 4px #1B2F48; padding: 0.1em 0.5em; color:#1B2F48;'>共通仕様</h4> <div style='width:100%; margin:10px;'>   <p style='font-weight:bold; color:#616161;'>＜HTTPリクエストヘッダ＞</p>   <div style='display:table; margin-left:10px; background-color:#29659b;'>     <div style='display:table-cell; min-width:130px; padding:9px; border:1px solid #fff; color:#fff;'>項目</div>     <div style='display:table-cell; width:85%; padding:9px; border:1px solid #fff; color:#fff;'>仕様</div>   </div>   <div style='display:table; margin-left:10px;'>     <div style='display:table-cell; min-width:130px; padding:9px; border:1px solid #fff; color:#fff; background-color:#29659b;'>プロトコル</div>     <div style='display:table-cell; width:85%; padding:9px; border:1px solid #fff; background-color:#f8f8f8;'>HTTP1.1/HTTPS</div>   </div>   <div style='display:table; margin-left:10px;'>     <div style='display:table-cell; min-width:130px; padding:9px; border:1px solid #fff; color:#fff; background-color:#29659b;'>charset</div>     <div style='display:table-cell; width:85%; padding:9px; border:1px solid #fff; background-color:#f8f8f8;'>UTF-8</div>   </div>   <div style='display:table; margin-left:10px;'>     <div style='display:table-cell; min-width:130px; padding:9px; border:1px solid #fff; color:#fff; background-color:#29659b;'>content-type</div>     <div style='display:table-cell; width:85%; padding:9px; border:1px solid #fff; background-color:#f8f8f8;'>application/json</div>   </div>   <div style='display:table; margin-left:10px;'>     <div style='display:table-cell; min-width:130px; padding:9px; border:1px solid #fff; color:#fff; background-color:#29659b;'>domain_name</div>     <div style='display:table-cell; width:85%; padding:9px; border:1px solid #fff; background-color:#f8f8f8;'>       本番環境：api.gmo-aozora.com</br>       開発環境：stg-api.gmo-aozora.com     </div>   </div>   <div style='display:table; margin-left:10px;'>     <div style='display:table-cell; min-width:130px; padding:9px; border:1px solid #fff; color:#fff; background-color:#29659b;'>メインURL</div>     <div style='display:table-cell; width:85%; padding:9px; border:1px solid #fff; background-color:#f8f8f8;'>       https://{domain_name}/ganb/api/personal/{version}</br>       <span style='border-bottom:solid 1px;'>Version:1.x.x</span> の場合</br>       　https://api.gmo-aozora.com/ganb/api/personal/<span style='border-bottom:solid 1px;'>v1</span>     </div>   </div> </div> <div style='margin:20px 10px;'>   <p style='font-weight:bold; color:#616161;'>＜リクエスト共通仕様＞</p>   <p style='padding-left:20px; font-weight:bold; color:#616161;'>NULLデータの扱い</p>   <p style='padding-left:40px;'>パラメータの値が空の場合、またはパラメータ自体が設定されていない場合、どちらもNULLとして扱います</p> </div> <div style='margin:20px 10px;'>   <p style='font-weight:bold; color:#616161;'>＜レスポンス共通仕様＞</p>   <p style='padding-left:20px; font-weight:bold; color:#616161;'>NULLデータの扱い</p>   <ul>     <li>レスポンスデータ</li>       <ul>         <li style='list-style-type:none;'>レスポンスデータの値が空の場合または、レスポンスデータ自体が設定されない場合は「項目自体を設定しません」と記載</li>       </ul>     <li>配列</li>       <ul>         <li style='list-style-type:none;'>配列の要素の値が空の場合は「空のリスト」と記載</li>         <li style='list-style-type:none;'>配列自体が設定されない場合は「項目自体を設定しません」と記載</li>       </ul>   </ul> </div> <div style='margin:20px 10px;'>   <p style='font-weight:bold; color:#616161;'>＜更新系APIに関する注意事項＞</p>   <ul>     <li style='list-style-type:none;'>更新系処理がタイムアウトとなった場合、処理自体は実行されている可能性がありますので、</li>     <li style='list-style-type:none;'>再実行を行う必要がある場合は必ず照会系の処理で実行状況を確認してから再実行を行ってください</li>   </ul> </div> 
 *
 * API version: 1.1.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VAccount struct {
	// 振込入金口座ID 半角数字 振込入金口座を識別するID 
	VaId string `json:"vaId"`
	// 支店コード 半角数字 
	VaBranchCode string `json:"vaBranchCode"`
	// 支店名 全角文字 
	VaBranchName string `json:"vaBranchName"`
	// 支店名カナ 半角文字 
	VaBranchNameKana string `json:"vaBranchNameKana"`
	// 口座番号 半角数字 
	VaAccountNumber string `json:"vaAccountNumber"`
	// 口座名義カナ 半角文字 
	VaHolderNameKana string `json:"vaHolderNameKana"`
	// 振込入金口座　種類コード 半角数字 ・1=期限型 ・2=継続型 
	VaTypeCode string `json:"vaTypeCode"`
	// 振込入金口座　種類名 全角文字 振込入金口座　種類コードの名称 
	VaTypeName string `json:"vaTypeName"`
	// 振込入金口座　状態コード 半角数字 ・1=利用可能 ・2=停止中 ・3=削除済 
	VaStatusCode string `json:"vaStatusCode"`
	// 振込入金口座　状態名 全角文字 振込入金口座　状態コードの名称 
	VaStatusName string `json:"vaStatusName"`
	// 振込入金口座　状態変更可能コード 半角数字 現在の口座状態から変更可能な口座状態を表したコード値 ・1=停止・削除 ・2=再開・削除 ・3=該当なし 
	VaStatusChangePossibleCode string `json:"vaStatusChangePossibleCode"`
	// 発行日時 半角文字 YYYY-MM-DDTHH:MM:SS+09:00形式 
	VaIssueDateTime string `json:"vaIssueDateTime"`
	// 状態変更日時 半角文字 YYYY-MM-DDTHH:MM:SS+09:00形式 状態が変更されている場合のみ設定されます 該当しない場合は項目自体を設定しません 
	VaChangeStatusDateTime string `json:"vaChangeStatusDateTime,omitempty"`
	// 削除日時 半角文字 YYYY-MM-DDTHH:MM:SS+09:00形式 状態コードが以下の場合のみ設定されます 該当しない場合は項目自体を設定しません ・3=削除済 
	VaCloseDateTime string `json:"vaCloseDateTime,omitempty"`
	// 有効期限日時 半角文字 YYYY-MM-DDTHH:MM:SS+09:00形式 種類コードが以下の場合のみ設定されます 該当しない場合は項目自体を設定しません ・2=期限型 
	ExpireDateTime string `json:"expireDateTime,omitempty"`
	// 最終入金日 半角文字 YYYY-MM-DD形式 入金がない場合は項目自体を設定しません 
	LatestDepositDate string `json:"latestDepositDate,omitempty"`
	// 最終入金金額 半角数字 入金がない場合は項目自体を設定しません 
	LatestDepositAmount string `json:"latestDepositAmount,omitempty"`
	// 最終入金日入金回数 半角数字 入金がない場合は項目自体を設定しません 
	LatestDepositCount string `json:"latestDepositCount,omitempty"`
	// 入金口座ID 半角数字 入金先の口座を識別するID 
	RaId string `json:"raId"`
	// 入金口座　支店コード 半角数字 
	RaBranchCode string `json:"raBranchCode"`
	// 入金口座　支店名 全角文字 
	RaBranchName string `json:"raBranchName"`
	// 入金口座　口座番号 半角数字 
	RaAccountNumber string `json:"raAccountNumber"`
	// 入金口座名義 全角文字 
	RaHolderName string `json:"raHolderName"`
}
